apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myapi
  name: myapi
spec:
  automountServiceAccountToken: false
  containers:
  - image: timotacr.azurecr.io/myapi:v6
    imagePullPolicy: Always
    name: myapi
    volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
    ports:
      - containerPort: 80
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
  restartPolicy: Never

